repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: local
    hooks:
      # Auto-format staged files on pre-commit
      - id: autoformat-snake-case
        name: Autoformat Python filenames to snake_case
        entry: python scripts/format_to_snake_case.py --staged
        language: system
        types: [python]
        stages: [pre-commit]
        pass_filenames: false

      # Double-check that everything is correct before commit
      - id: verify-snake-case
        name: Verify all Python filenames are snake_case
        entry: python scripts/format_to_snake_case.py --check
        language: system
        types: [python]
        stages: [pre-commit]
        pass_filenames: true
